import "./pricefeeds";
import "./priceaggregator";
import "./feedsregistry";
import "./examplepricefeedconsumer";
import "./multipricefeed";
import "./pricefeedfactory";
import "./newfpo";
import "./p2pfactory";
import "./upgradeableP2pFactory";
